In [208]:
#1. Import the numpy package under the name np (★☆☆)hint: 


In [209]:
import numpy as np

In [210]:
# 2. Create a null vector of size 10 (★☆☆)
hint: np.zeros

In [211]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [212]:
###3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)hint: array[4]


In [213]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [214]:
a[5]=1

In [215]:
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [216]:
# 4. Create a vector with values ranging from 10 to 49 (★☆☆) hint: arange

In [217]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [218]:
### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) hint: reshape

In [219]:
c = np.arange(0,9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [220]:
### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) hint: np.nonzero

In [221]:
d = np.array([1,2,0,0,4,0])
np.nonzero (d)

(array([0, 1, 4]),)

In [222]:
### 7. Create a 3x3 identity matrix (★☆☆) hint: np.eye

In [223]:
identity_matrix = np.zeros(9).reshape(3,3)
identity_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [224]:
identity_matrix = np.eye(3,3) 
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [225]:
###8. Create a 3x3x3 array with random values (★☆☆) hint: np.random.random

In [226]:
f = np.random.random ((3,3,3))
f

array([[[0.59792607, 0.52766448, 0.93097582],
        [0.44775132, 0.17239615, 0.78084678],
        [0.33567862, 0.27506255, 0.49948369]],

       [[0.94042832, 0.7699324 , 0.030699  ],
        [0.48577588, 0.84081027, 0.72564578],
        [0.7714988 , 0.42235597, 0.82291984]],

       [[0.12374579, 0.58535735, 0.44051287],
        [0.81790297, 0.63973254, 0.94346814],
        [0.58131958, 0.22915017, 0.22542729]]])

In [227]:
### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) hint: min, max

In [228]:
g = np.random.random ((10,10))
g

array([[0.22327725, 0.01785653, 0.93086918, 0.04431077, 0.09236585,
        0.35681505, 0.15523134, 0.16416697, 0.55815546, 0.70367775],
       [0.08304782, 0.29913228, 0.04818634, 0.32838029, 0.85787374,
        0.82215572, 0.5316451 , 0.12181809, 0.03016959, 0.0018602 ],
       [0.80818204, 0.68696582, 0.79345318, 0.86738089, 0.91120256,
        0.74917571, 0.88134292, 0.07311401, 0.62427633, 0.43879792],
       [0.06059488, 0.72351154, 0.37534592, 0.91352454, 0.06228803,
        0.14016293, 0.02267688, 0.80027741, 0.89376993, 0.26404597],
       [0.13330168, 0.00813564, 0.53137219, 0.7979226 , 0.52193713,
        0.06045174, 0.84464963, 0.9163635 , 0.42434844, 0.98231781],
       [0.8347448 , 0.93080655, 0.5964941 , 0.50038629, 0.82319104,
        0.46281952, 0.29380209, 0.25641211, 0.44761677, 0.10853537],
       [0.15981468, 0.16824276, 0.5330886 , 0.28272632, 0.22440695,
        0.46187343, 0.26004854, 0.99466081, 0.43209248, 0.63671202],
       [0.42363497, 0.02918378, 0.5873195

In [229]:
np.min(g)

0.0018602049630186412

In [230]:
np.max(g)

0.9946608069673045

In [231]:
### 10. Create a random vector of size 30 and find the mean value (★☆☆) hint: mean

In [232]:
random_vec_3 = np.random.random()
random_vec_3

0.761619370057027

In [233]:
mean_vec = np.mean(random_vec_3)
mean_vec

0.761619370057027

In [234]:
###11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) hint: np.diag


In [235]:
array_5_5 = np.random.random ((5,5))
array_5_5

array([[0.22518997, 0.97264692, 0.91414538, 0.88490753, 0.95787402],
       [0.82599455, 0.80025073, 0.78533529, 0.72355238, 0.69099748],
       [0.01406763, 0.52126631, 0.11115005, 0.14787381, 0.55175749],
       [0.75533356, 0.19848124, 0.90387372, 0.07970626, 0.60858095],
       [0.98305943, 0.82098808, 0.54540512, 0.25800516, 0.58153833]])

In [236]:
diagonal_5_5= np.diag(np.arange(1,5), k= -1)
print(diagonal_5_5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [237]:
###  12. Normalize a 5x5 random matrix (★☆☆) hint: (x -mean)/std

In [238]:
normal_matrix_5_5= np.random.random ((5,5))
normal_matrix_5_5

array([[0.0681063 , 0.44213367, 0.39219333, 0.06778995, 0.64429793],
       [0.7325006 , 0.7860168 , 0.31994789, 0.78445669, 0.33005812],
       [0.8686914 , 0.18421036, 0.00492093, 0.93665965, 0.10864562],
       [0.25164613, 0.04689305, 0.24175846, 0.56544208, 0.46391146],
       [0.91475715, 0.27001093, 0.42123954, 0.9036179 , 0.31376658]])

In [239]:
min_normal_mat = np.min(normal_matrix_5_5)
min_normal_mat

0.004920926276343107

In [240]:
max_normal_mat = np.max(normal_matrix_5_5)
max_normal_mat

0.9366596455364704

In [241]:
difference_max_min= max_normal_mat-min_normal_mat
difference_max_min

0.9317387192601273

In [242]:
mean_normal_mal= np.mean(normal_matrix_5_5)
mean_normal_mal

0.44254690097477756

In [243]:
std_nomal_mat= np.std(normal_matrix_5_5)
std_nomal_mat

0.29646224490845985

In [244]:
### Normalize with formula: (x -mean)/std
normalized = ((normal_matrix_5_5-mean_normal_mal)/(std_nomal_mat))

In [245]:
normalized

array([[-1.26302964e+00, -1.39386162e-03, -1.69848158e-01,
        -1.26409673e+00,  6.80528585e-01],
       [ 9.78045953e-01,  1.15856204e+00, -4.13540034e-01,
         1.15329960e+00, -3.79437107e-01],
       [ 1.43743260e+00, -8.71397787e-01, -1.47616090e+00,
         1.66669703e+00, -1.12628601e+00],
       [-6.43929454e-01, -1.33458429e+00, -6.77281643e-01,
         4.14539066e-01,  7.20650270e-02],
       [ 1.59281748e+00, -5.81982955e-01, -7.18720804e-02,
         1.55524357e+00, -4.34390306e-01]])

In [246]:
### Normalized with alternative formula y = (y-xmin)/(xmax-xmin)

In [247]:
normalized_2 = (normal_matrix_5_5-min_normal_mat)/(max_normal_mat-min_normal_mat)
normalized_2

array([[0.06781447, 0.46924394, 0.41564486, 0.06747495, 0.68621921],
       [0.7808838 , 0.83832072, 0.33810655, 0.83664631, 0.34895748],
       [0.92705224, 0.19242458, 0.        , 1.        , 0.1113238 ],
       [0.26480085, 0.04504709, 0.25418879, 0.6015862 , 0.49261722],
       [0.97649288, 0.28451109, 0.44681906, 0.96453754, 0.33147238]])

In [248]:
### 13. How to find common values between two arrays? (★☆☆) hint: np.intersect1d

In [249]:
array_1 = [1,3,5,7]
array_2= [1,2,4,10]

np.intersect1d(array_1, array_2)

array([1])

In [250]:
### 14. Create a random vector of size 10 and sort it

In [251]:
random_vec=np.random.random(10)
random_vec

array([0.7436818 , 0.58701848, 0.91203537, 0.59899894, 0.9081575 ,
       0.55113335, 0.71679049, 0.30826624, 0.37079816, 0.41809157])

In [252]:
np.sort(random_vec)

array([0.30826624, 0.37079816, 0.41809157, 0.55113335, 0.58701848,
       0.59899894, 0.71679049, 0.7436818 , 0.9081575 , 0.91203537])

In [253]:
### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆) hint: argmax

In [254]:
random_vec_15 =np.random.random(10)

In [255]:
random_vec_15

array([0.91337922, 0.30710248, 0.87896478, 0.01066171, 0.73453688,
       0.75491664, 0.69971582, 0.03491402, 0.31116391, 0.48890462])

In [256]:
max_val_rvect_15 = np.argmax(random_vec_15)

In [257]:
max_val_rvect_15

0

In [258]:
### replace max by 0:
random_vec_15[7]=0

In [259]:
random_vec_15

array([0.91337922, 0.30710248, 0.87896478, 0.01066171, 0.73453688,
       0.75491664, 0.69971582, 0.        , 0.31116391, 0.48890462])

In [260]:
### 16. Subtract the mean of each row of a matrix (★★☆) hint: mean(axis=,keepdims=)

In [261]:
matrix_16 = np.random.random((3,3,))
matrix_16

array([[0.15632524, 0.17619863, 0.16683781],
       [0.45632434, 0.84118198, 0.73010743],
       [0.11051118, 0.05662965, 0.36790448]])

In [262]:
mean_by_row = np.mean(matrix_16, axis=1).reshape((3,1))
mean_by_row

array([[0.16645389],
       [0.67587125],
       [0.17834844]])

In [263]:
### 17. How to get the n largest values of an array (★★★) 
### Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

In [264]:
n = 5

In [265]:
array_17 = np.arange(10000)
np.random.shuffle(array_17)
array_17

array([4731, 1917, 8741, ..., 4258,  348,  944])

In [266]:
# argsort will sort the values
sorted_array = np.argsort(array_17)[-5:]
sorted_array

array([8894, 5347, 1830, 9624, 7323])

In [267]:
### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36) hint: np.where

In [268]:
array_18 = np.random.randint(0,10,(5,3))
array_18

array([[2, 9, 1],
       [3, 6, 0],
       [7, 3, 2],
       [0, 3, 2],
       [5, 9, 3]])

In [269]:
## ATTENTION .where() uses a boolean condition so if TRUE the value will not be replaced.
replaced_array_18= np.where((array_18<4),array_18,array_18**2 )
replaced_array_18

array([[ 2, 81,  1],
       [ 3, 36,  0],
       [49,  3,  2],
       [ 0,  3,  2],
       [25, 81,  3]])